#!/usr/bin/env python3

#
# Copyright (C) 2026 Anton
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os
import sys
import agent

agent.set_weight(os.path.basename(__file__), 0)  # Validation step, no task progress at all

data = json.load(sys.stdin)
host = data["host"]
old_host = os.environ.get("TRAEFIK_HOST", "")

if host != old_host and agent.http_route_in_use(domain=host):
    agent.set_status("validation-failed")
    json.dump(
        [
            {
                "field": "host",
                "parameter": "host",
                "value": host,
                "error": "domain_already_used_in_traefik",
            }
        ],
        fp=sys.stdout,
    )
    sys.exit(2)
