#!/bin/bash

#
# Copyright (C) 2026 Anton
# SPDX-License-Identifier: GPL-3.0-or-later
#

# If the control reaches this step, the service can be enabled and started

systemctl --user enable nextcloud-mcp.service
systemctl --user restart nextcloud-mcp.service
