#!/usr/bin/env python3

#
# Copyright (C) 2026 Anton
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys

import agent

request = json.load(sys.stdin)
original_environment = request["environment"]

for evar in [
    "TRAEFIK_HOST",
    "TRAEFIK_HTTP2HTTPS",
    "LETS_ENCRYPT",
    "NEXTCLOUD_HOST",
    "NEXTCLOUD_USERNAME",
    "OLLAMA_BASE_URL",
    "OLLAMA_EMBEDDING_MODEL",
    "ENABLE_SEMANTIC_SEARCH",
]:
    if evar in original_environment:
        agent.set_env(evar, original_environment[evar])
